### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by iddm** [vityafx/toornament-rs#1]
- [x] `travis.ci` support with uploading book automatically
- [x] writing an example which calls all the API functions and demonstrates the work in the examples/workflow.rs file
- [x] writing a book (by `mdbook`)
- [x] remote iterable collections=
- [x] releasing as 1.0 version
